### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by oreillyjohn** [wikiwidget/wikipedia-widget#11] opened 2016-11-18 11:29 UTC
Images not showing on 10.12.1

<img width="852" alt="screen shot 2016-11-18 at 11 28 09" src="https://cloud.githubusercontent.com/assets/17743138/20428640/1c6f9670-ad82-11e6-83c0-c2b41316f2b1.png">

**Comment by sbliven** [comment] 2016-11-23 15:21
Duplicate of #8.

Yes, it has been forever since this project got an update. Sorry, Apple provides zero tools for debugging widgets and I have minimal time for this. Pull requests are greatly appreciated.

**Closed as completed by sbliven** 2016-11-23 15:21 UTC
